### ISSUE TITLE
Stacktrace printed to console when no recipe is found in main page

### ISSUE THREAD

**Issue by JeMaJa** [JeMaJa/weekmenu#8]
When no recipe is found in the main page.
A stack trace is logged in the console. 
This is not needed. Just logging to Debug and Warning is sufficient

**Comment by HenriquePinto333** [comment]
Hey! I think I can handle this. Wouldn't it be more Helpful to throw an Exception and catch it to print a custom message or handle it with a java Optional? Tell me anything, I can help you.

**Comment by JeMaJa** [comment]
> Hey! I think I can handle this. Wouldn't it be more Helpful to throw an Exception and catch it to print a custom message or handle it with a java Optional? Tell me anything, I can help you.

Hi @HenriquePinto333 , feel free to do so!
I've included the applications.properties file in my latest commit, so this should allow you to run the application locally and test.

There already is an error message going to the users as well. I believe it also already throws a NotFoundException, however I'm not sure if it always does this. Perhaps you have ideas to make it nicer.
Enjoy!
